# Base image
FROM node:20-alpine AS base

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY . .

# Expose port (default for NestJS)
EXPOSE 3000

# Start app in dev mode
CMD ["npm", "run", "start:dev"]
